# This is a basic workflow to help you get started with Actions

name: CI


env:
  MIRROR_URL: "git@github.com:barbara-menezes/docker.git"
  EXECUTABLES: "result/node_modules"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches-ignore:    
      - 'ga-ignore-'
  pull_request:
    branches-ignore:    
      - 'ga-ignore-'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check_coding_style"
  push_to_mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - uses: pixta-dev/repository-mirroring-action@v1
       with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:                           
          ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          
  check_coding_style:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - uses: actions/setup-node@v3
       with:
          node-version: 12
     - run: npm install

      # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
          check.sh $(pwd) $(pwd),
          echo "::error"
          
  check_program_compilation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - uses: actions/setup-node@v3
       with:
          node-version: 12
     - run: npm install

      # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
          check.sh $(pwd) $(pwd),
          echo "::error"
          
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3
       with:
          fetch-depth: 0
     - uses: actions/setup-node@v3
       with:
          node-version: 12
     - run: npm install

      # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
          check.sh $(pwd) $(pwd),
          echo "::error"
